# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/grafteopy',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/grafteopy',
                'lib_path': 'grafteopy'},
  'syms': {'grafteopy.core': {'grafteopy.core.foo': ('core.html#foo', 'grafteopy/core.py')}}}